#!/usr/bin/env python3
"""Copy data/foods.json into the marked block in docs/index.html.

The page has to be self-contained, which means the food table is inlined. That
creates a way for the page to drift away from the real table, so this script is
the only thing allowed to write that block, and --check makes a stale page fail
the verify rather than quietly serving old numbers.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "docs", "index.html")
TABLE = os.path.join(ROOT, "data", "foods.json")

BEGIN = "/* FOOD_TABLE:BEGIN  generated by scripts/sync_page_data.py, do not edit by hand */"
END = "/* FOOD_TABLE:END */"


def block_text() -> str:
    with open(TABLE) as fh:
        table = json.load(fh)
    return "const FOOD_TABLE = " + json.dumps(table, indent=2) + ";"


def split_page(text: str):
    i = text.find(BEGIN)
    j = text.find(END)
    if i < 0 or j < 0 or j < i:
        raise SystemExit("docs/index.html has no FOOD_TABLE block markers")
    return text[: i + len(BEGIN)], text[i + len(BEGIN) : j], text[j:]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report a stale page instead of rewriting it")
    args = ap.parse_args(argv)

    with open(PAGE) as fh:
        page = fh.read()
    head, current, tail = split_page(page)
    wanted = "\n" + block_text() + "\n"

    if args.check:
        if current != wanted:
            print("docs/index.html carries a food table that is not data/foods.json",
                  file=sys.stderr)
            return 1
        n = len(json.loads(open(TABLE).read())["foods"])
        print(f"docs/index.html food table is in sync with data/foods.json ({n} foods)")
        return 0

    with open(PAGE, "w") as fh:
        fh.write(head + wanted + tail)
    print("docs/index.html food table updated from data/foods.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
